### ISSUE TITLE
Support for Webpack from Aurelia CLI

### ISSUE THREAD

**Issue by khuongduybui** [aurelia-toolbelt/aurelia-toolbelt#55]
The getting started page is not very user-friendly.

> We don't go through the painful details of how you should configure your `aurelia-cli`, `webpack` or `fusebox`. The plugin will **work with all of them based on the basic configurations** that you should know when using each.

To test it out, I created a new project with Aurelia CLI, which now uses webpack by default.
Then I ran `yarn add aurelia-toolbelt`, and added `aurelia.use.plugin(PLATFORM.moduleName('aurelia-toolbelt'));` as suggested. Then I ran `aurelia run` and immediately got errors, such as:

> ERROR in ./node_modules/aurelia-toolbelt/dist/commonjs/components/jquery/block-ui/aut-block-ui.js
Module not found: Error: Can't resolve './SharedOptions' in '~/test/node_modules/aurelia-toolbelt/dist/commonjs/components/jquery/block-ui'

> ERROR in ./node_modules/aurelia-toolbelt/dist/commonjs/components/jquery/metis-menu/aut-metis-menu.html
Module not found: Error: Can't resolve 'metismenu/dist/metismenu.css' in '~/test/node_modules/aurelia-toolbelt/dist/commonjs/components/jquery/metis-menu'

**Comment by shahabganji** [comment]
Dear @khuongduybui,

> The getting started page is not very user-friendly.

We have plans to make a complete overhaul. So it will look more like the bootstrap page.

> To test it out, I created a new project with Aurelia CLI,

Your error is due to the fact that some of the jquery plugins are not easy to configure, neither in webpack nor in other formats, so we have created startup projects [here](https://github.com/aurelia-toolbelt) that you could take a look, you need to make some changes in webpack.js to set the wheel in motion. 

[This](https://github.com/aurelia-toolbelt/aut-webpack4-aspnetcore-starter-kit) is the starter kit for [webpack 4](https://github.com/aurelia-toolbelt/aut-webpack4-aspnetcore-starter-kit/blob/master/package.json#L64).

if you still have any problems please let me know.

**Comment by shahabganji** [comment]
BTW, you should run this ```yarn add aurelia-toolbelt@0.9.2-alpha```, and I've added another starter kit for just webpack and no asp.net core, find it [here](https://github.com/aurelia-toolbelt/aut-webpack4-starter-kit). 

I ran ```au run --watch```

**Comment by HamedFathi** [comment]
@khuongduybui 
You should use `au run --watch` because of [this](https://github.com/aurelia/cli/issues/881) and [this](https://github.com/aurelia/cli/issues/863)

**Comment by khuongduybui** [comment]
I figured out the 2 errors; they are due to mis-case typos.

First one is [here](https://github.com/aurelia-toolbelt/aurelia-toolbelt/blob/master/src/components/jquery/block-ui/aut-block-ui.ts#L1): `from './SharedOptions'` should be `from './sharedOptions'`.

Second one is [here](https://github.com/aurelia-toolbelt/aurelia-toolbelt/blob/master/src/components/jquery/metis-menu/aut-metis-menu.html#L3): `"metismenu/dist/metismenu.css"` should be `"metismenu/dist/metisMenu.css"` (see [metismenu](https://github.com/onokumus/metismenu/tree/master/dist)).
