### ISSUE TITLE
abt-float-input needs to support value binding and required cascading

### ISSUE THREAD

**Issue by khuongduybui** [aurelia-toolbelt/aurelia-toolbelt#78]
An input control is almost useless without value binding. We should be able to write `<abt-float-input value.bind="foo" required></abt-float-input>` and eventually have `...<input value.bind="foo" required>...`

**Comment by HamedFathi** [comment]
@khuongduybui 

Thanks, I am so sorry It is my fault. I fixed it you can use it in next release.
Unfortunately, Aurelia does not support [Transparent Wrapper Components](https://github.com/aurelia/aurelia/issues/319) yet, so I should support all textbox attributes one by one in each control.

We will have an overhaul on Aurelia-Toolbelt. Something like this control should convert to a `custom attribute` instead of `custom control` like [at-float-label](https://github.com/aurelia-toolbelt/aurelia-toolbelt/blob/master/src/custom-attributes/jquery/float-label/at-float-label.ts). This control supports everything you want plus RTL.

**Comment by khuongduybui** [comment]
Thanks for the info. I didn't see `at-float-label` on https://aurelia-toolbelt.github.io/#/get-started

**Comment by HamedFathi** [comment]
@khuongduybui 

I know it has some problems yet. I should fix them first :)

**Comment by shahabganji** [comment]
@HamedFathi What's the state of this issue? Shall we close this and provide a release?

**Comment by HamedFathi** [comment]
I fixed it. Yes we can. 😊
